### ISSUE TITLE
Users timezone still applies after leaving server

### ISSUE THREAD

**Issue by KevinNovak** [KevinNovak/Friend-Time#10]
**Nathan** (Discord): "Hey just a quick question, i had a member in Discord that registered their country with Friend Time bot, but they have now left Discord, i'm still getting their time display when i use this, how can i remove that country time?"

**NovaKevin**: "If someone else in the server has their timezones set as that it will still show up, but if they left the server while the bot was down then there could be a problem. I'd need your server ID to manually remove the timezone

https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-"

**Comment by RedHotTrouble** [comment]
Hello NovaKevin, is it possible that you help me address this same issue in my Discord server?

**Comment by KevinNovak** [comment]
This issue should be fixed as of the latest change. Closing.
