### ISSUE TITLE
Support for threads

### ISSUE THREAD

**Issue by akwonder1** [KevinNovak/Friend-Time#102]
Currently the bot can be added to threads by pinging, however once added the bot doesn't parse any messages inside of those threads.

**Comment by FiraliaDev** [comment]
Having the same problem D:

**Comment by KevinNovak** [comment]
I'll look into adding this feature

**Comment by KevinNovak** [comment]
Friend Time can now respond to messages in threads after pinging it. Let me know if this does not work for you. Closing this request for now.
