### ISSUE TITLE
Bot frequently goes offline

### ISSUE THREAD

**Issue by fluidityt** [KevinNovak/Friend-Time#14]

**Comment by Antz72** [comment]
Same in ours, noticed for maybe two or three days

**Comment by anne-k** [comment]
It's going offline a lot lately, is something going on?

**Comment by kittyka0s** [comment]
same problem in our server - the bot is offline a lot. since I've been paying attention, the bot has been offline for 8 hours so far today

**Comment by littlelegsxx** [comment]
Same problem. Does anyone know if it will be working again or if there is another Bot that does the same?

**Comment by TheMoroney** [comment]
Same deal I would be willing to help fund hosting if that is the main issue.

**Comment by Antz72** [comment]
Been offline for at least a week now. Hoping for a fix soon as I really, really love the tool but I'm at the point where I'm almost ready to give up on it :(

**Comment by KevinNovak** [comment]
I have to do some investigating but I believe this is related to loading all server data into memory, which was probably a bad decision to start with. I plan converting this to use a database instead.

**Comment by TheMoroney** [comment]
Is this in the process of being fixed?

**Comment by littlelegsxx** [comment]
Can you let us know if/when this will be up and running again please?

**Comment by KevinNovak** [comment]
Friend Time should be back online as of today's changes. I'll leave this thread open for a bit to make sure the issue doesn't reappear. Thanks!

**Comment by phokingpuffy** [comment]
Bot has been going down a lot as of late. It seems to be down more than it is up. Any way to locally host it and if so, how do I do it?

**Comment by KevinNovak** [comment]
Hi @phokingpuffy, if you're still interested I've created the following document on [how to run Friend Time locally](https://github.com/KevinNovak/Friend-Time/blob/master/docs/running-locally.md).
