### ISSUE TITLE
Ability to set time zone of bots, webhooks, and subscribed server announcements

### ISSUE THREAD

**Issue by ryantheleach** [KevinNovak/Friend-Time#20]
![image](https://user-images.githubusercontent.com/141554/66920746-77960c80-f06b-11e9-8c29-741acc250a40.png)

It would be good if admins could set the timezone of bots and other users.

**Comment by KevinNovak** [comment]
With the recent update, admins can now set time zones for bots by using the `-ft set @bot` command.
