### ISSUE TITLE
Change "America" to "Americas"

### ISSUE THREAD

**Issue by sarahdlowe** [KevinNovak/Friend-Time#21]
Some users find it confusing to see cities out the US appended with `America/` given the strong association of America = USA, for example `America/Winnipeg`

Would it be possible to change `America` to `Americas` to be more clear that the region is for North and South America?

**Comment by KevinNovak** [comment]
I going to close this since Friend Time doesn't control the name of time zones. These names were determined by the [IANA](https://www.iana.org/time-zones) group.
