### ISSUE TITLE
Distinguish timezone of user triggering bot

### ISSUE THREAD

**Issue by JollySarah** [KevinNovak/Friend-Time#22]
Enhancement/feature Request:

The app is incredibly useful but one thing I feel is sorely needed is the ability to distinguish the timezone/location of the user that triggered the bot in the first place. If there's a lot of text or multiple time zones are entered into a messages (only the first time entered is converted) then it can get a little tricky.

Would it be possible to have the time zone of the user that triggered the bot to have their time zone and location displayed in the first line followed by a visual line break (even a single "-" would work) before the rest of the time zones and locations are displayed?

**Comment by KevinNovak** [comment]
I've made a change which italicizes and underlines the timezone of the user triggering the time conversion:
![See the following image](https://i.imgur.com/wySt5gA.png)

This should help distinguish which user/time zone is triggering the bot.
