### ISSUE TITLE
Bot going down

### ISSUE THREAD

**Issue by phokingpuffy** [KevinNovak/Friend-Time#23]
Time Bot seems to go down quite often. Everyday for hours on end. Is there a way to host it locally?

**Comment by KevinNovak** [comment]
Hi phokingpuffy, I've made some improvements recently which should make the bot more stable. I'll close this issue but if it becomes a problem again feel free to open a new issue.

As for hosting locally it is possible but not straightforward, and I don't have anything written up currently. It requires that you have Node.js 12 and a MySQL instance. In MySQL create a new database for Friend Time, and run the `scripts/create-database.sql` file to set up the appropriate tables and procedures. Once the database is setup, you can change the database settings in the `config/config.json` file. Then you'll need to obtain a discord bot token (there are many guides online). You can also place this token in the `config/config.json` file. After this you'll need to install the dependencies by running `npm install`, and start the bot by running either `npm start` or `node app.js`.

**Comment by KevinNovak** [comment]
Hi phokingpuffy, if you're still interested I've created the following document on [how to run Friend Time locally](https://github.com/KevinNovak/Friend-Time/blob/master/docs/running-locally.md).
