### ISSUE TITLE
Error in "am / pm"

### ISSUE THREAD

**Issue by smileperez** [KevinNovak/Friend-Time#32]
hello,

There are errors in indicating the time, for example, these:
1.
![изображение](https://user-images.githubusercontent.com/24222121/71936378-4a648080-31ba-11ea-9848-1d4654f4d48a.png)

But in reality: 
Europe/Riga: 11:00 **pm**
Europe/Moscow: 12:00 pm

2.
![изображение](https://user-images.githubusercontent.com/24222121/71936416-5ea87d80-31ba-11ea-8944-e80086fe3598.png)

But in reality: 
Europe/Riga: 12:00 am
Europe/Moscow: 1:00 **pm**

**Comment by KevinNovak** [comment]
Hi @smileperez,

I believe there is some confusion between 12am and 12pm. Officially, 12am is midnight, and 12pm is noon (See https://en.wikipedia.org/wiki/12-hour_clock#Confusion_at_noon_and_midnight).

In your first example, you type 12pm, which is noon, and 1 hour before noon is 11am. In your second example, you type 12am, which is midnight, and 1 hour after midnight is 1am.

Hopefully this helps!
