### ISSUE TITLE
Incorrect time returned from using "ago"

### ISSUE THREAD

**Issue by rosareven** [KevinNovak/Friend-Time#33]
The use of "ago" (for example 1 hour ago) returns incorrect time. 

Have checked that -ft time returns the correct time, so there's no telling where the bot got the time from for "ago".

Please see screenshot for the problem in action.

![Discord_EZYDZG6U8E](https://user-images.githubusercontent.com/17244066/74561699-fb4fff00-4f60-11ea-8fb3-3dcc50cbe1d5.jpg)

**Comment by KevinNovak** [comment]
Hi @rosareven, I see the problem. This bug is caused by the fact that Friend Time is using it's local time a reference point when doing the conversion. There should be a fix coming. Thanks for making me aware of this.

**Comment by KevinNovak** [comment]
After looking into this, I decided to remove the ability for Friend Time to convert time formats like "1 hour ago" or "45 minutes later". There were other issues around this type of format that would require significant rework. I'd like to get this working in the future but for now Friend Time won't attempt to try to convert these formats.

**Comment by rosareven** [comment]
It's for the best. It does get unintentionally triggered too often in ordinary chit chat. Thanks for your update.
