### ISSUE TITLE
Option for answer in Chat or DM

### ISSUE THREAD

**Issue by Kyusetzu** [KevinNovak/Friend-Time#38]
Since my server has quiet a few people using the bot, I would like to have the bot announce the time in the chat like it did in the past.
So I'd like a config option for switching between the old message and dm'ing.

**Comment by GhostTheSlayer** [comment]
There is already an option for that if your an admin use the following
> -ft config mode list
And if you wish to switch it back use:
> -ft config mode react

**Comment by Kyusetzu** [comment]
Oh! Thanks. Seems I was to dumb to read. lol
