### ISSUE TITLE
Send reminder to set time zone in direct message rather than public chat

### ISSUE THREAD

**Issue by eveevec** [KevinNovak/Friend-Time#40]
I wanted to know if there was a way that the bot will only send reminders to a certain role that doesn't have their time rather then everyone in the server? I manage a server where we have a general chat for everyone and a specific chat for gamers and i only want reminders to go out to certain members not all.

**Comment by KevinNovak** [comment]
Friend Time only sends reminders if the person who mentioned a time doesn't have a time zone set. I could see a problem however if you don't want this reminder to be sent in a general chat, I think this would be better sent in a private message. I'll look into changing this.

**Comment by KevinNovak** [comment]
With the recent update, Friend Time now only sends reminders in DMs (rather than in the server). Servers and users can also disable these reminders if desired.
