### ISSUE TITLE
Can't add bot to server because it has yet to be verified

### ISSUE THREAD

**Issue by Moonkis** [KevinNovak/Friend-Time#56]
This is the error you get when trying to add it:
![image](https://user-images.githubusercontent.com/1334297/95986215-ed22ed00-0e25-11eb-8833-2cd7eb64a5c5.png)

Following docs:
https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting

**Comment by scottbucher** [comment]
This issue has been well documented in our support server (https://discord.gg/GQcBR8e). It is not an issue with the bot not being verified and has to do with the gateway intents which Kevin contacted discord months ago but they have failed to get back to him. He has since contacted them again and we are waiting for this to be resolved.

**Comment by MaesterOban** [comment]
In the interim I'm trying to run the bot locally and I am experience an issue with a line item with "mulitlingual support"

**Comment by scottbucher** [comment]
Firstly this issue thread isn't the place to get support for self-hosting. Secondly, I would ensure you have installed all the required dependencies.

**Comment by Moonkis** [comment]
@scottbucher That's good that it's known and is actively being looked into awaiting response. I don't (clearly!) hang out in the support Discord server so I wouldn't know from the Github tracker itself. I suggest it remains an open ticket until it's resolved as the only way currently is to self host it, and *hopefully* people read the issue tracker.

I got my response so I'm happy either way.

**Comment by KaiFireborn** [comment]
Sad the bot cannot be invited. It's exactly what I need

**Comment by GalGreenfield** [comment]
Same for me. I hope the matter can be resolved soon.

**Comment by GalGreenfield** [comment]
> In the interim I'm trying to run the bot locally and I am experience an issue with a line item with "mulitlingual support"
> ![image](https://user-images.githubusercontent.com/72513491/96069141-950ed980-0e6b-11eb-9343-388fbc640d1c.png)

Did you check the logs and find the reason? Maybe the bot's author using a translator `npm` package and there's a problem with it.

**Comment by scottbucher** [comment]
This issue has been fixed, thanks.
