### ISSUE TITLE
Unexpected Token while attempting to Self-Host

### ISSUE THREAD

**Issue by MaesterOban** [KevinNovak/Friend-Time#57]
When following the self-hosting.md guide I receive the following error when running "npm start"
![image](https://user-images.githubusercontent.com/72513491/96069266-d606ee00-0e6b-11eb-9677-086a4de5bdf3.png)

**Comment by KevinNovak** [comment]
What Node.js version are you using? If you are using <14 can you try upgrading to Node.js 14?

**Comment by MaesterOban** [comment]
@KevinNovak - Thank you!  I can't believe I didn't check that, I was on an older machine messing around and running v12.14.1 - now that I'm up to date I'm good!

**Comment by KevinNovak** [comment]
Thanks for making me aware of this! I've updated the places where node versions are mention to say that node v14 is required.
