### ISSUE TITLE
friend time not working

### ISSUE THREAD

**Issue by HysteriaVybe** [KevinNovak/Friend-Time#58]
So recently on a friend's server friend time just suddenly stopped working and so we tried to kick it and invite it back to see if it would work but all we got was this. please help 
![friend](https://user-images.githubusercontent.com/74262709/98711036-78729e00-2352-11eb-9e21-0e522dd804c3.PNG)

**Comment by KevinNovak** [comment]
This issue has been corrected. Please try inviting the bot again.
