### ISSUE TITLE
Daylight savings time not working

### ISSUE THREAD

**Issue by ExoCode17** [KevinNovak/Friend-Time#6]
I noticed the bot doesn't take into consideration DST! Or there's a way to tell it?

**Comment by KevinNovak** [comment]
It should work with daylight savings, can you send me an example of what you're seeing?

**Comment by TheDoctor2211** [comment]
Friend TimeBOTToday at 02:10
America/Cancun: 9:10 pm
Europe/London: 3:10 am

we were testing this today and my uk time is a hour later than it is, I think this is a daylight time zone issue

**Comment by KevinNovak** [comment]
Closing this issue as I have not heard of another occurrence. Please feel free to open a new issue if this occurs again.
