### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Atrate** [KevinNovak/Friend-Time#61]
It would be beneficial if you included a LICENSE file for your project (and mentioned in the README it only applies to the code, not the image assets).

Without a LICENSE in place, the code is implicitly All Rights Reserved, which means people cannot fork your code and legally make contributions to your repo.

I would suggest, as I always do, the GPLv3. Here are the instructions for including a LICENSE in your repo: https://www.gnu.org/licenses/gpl-howto.html

**Comment by scottbucher** [comment]
Not having a license is on purpose because the bot is intended to be All Rights Reserved though I agree this could be specified more clearly in the README.

**Comment by KevinNovak** [comment]
I would consider a license so long as the license prohibited the use of Friend Time for commercial purposes. I'm not aware of any open source license that does, so I decided not to include a license.

**Comment by Atrate** [comment]
@KevinNovak You may want to check out the Commons Clause License for that:
https://commonsclause.com/

As far as I understand, it's a clause that can be applied to any existing license (GPL, Apache, etc.) in order to prohibit using it for commercial purposes.

**Comment by KevinNovak** [comment]
I ended up implementing the Apache 2.0 license with the Commons Clause. The license can now be found [here](https://github.com/KevinNovak/Friend-Time/blob/master/LICENSE.md). Thanks for the suggestion!
