### ISSUE TITLE
Reply instead of message

### ISSUE THREAD

**Issue by mattben** [KevinNovak/Friend-Time#65]
Feature request:
How hard would it be to change all the direct messages in to one reply to a message?

Example

mattben
guys is 4pm good?

   mattben guys is 4pm good?
Friend Time 
4pm pst is 5pm mnt, 7pm est, 12am gmt

**Comment by KevinNovak** [comment]
This can be accomplished with "list" mode (`-ft config mode list`).

**Comment by mattben** [comment]
Thank you!

**Comment by KevinNovak** [comment]
No problem!
