### ISSUE TITLE
Set time zones of other users

### ISSUE THREAD

**Issue by jman1113** [KevinNovak/Friend-Time#7]
I'd like to be able to set a user's time zone myself instead of teaching the entire server how to follow directions. 
So say -ft @user set [timezone]??

**Comment by KevinNovak** [comment]
A number of users have requested admin commands (setting users timezones, changing what timezones are shown in the list, etc), I'll probably do them all together in an update.

**Comment by jman1113** [comment]
Awesome! I appreciate the reply

**Comment by mahoromax** [comment]
Just tried to set my timezone.
It didnt take CET, CEST, UTC+1 GMT+1
the linked map is suggesting CET which the bot doesnt accept

**Comment by jman1113** [comment]
mahoromax if you have to type whatever is before the parenthesis. 
So if you chose say.... Zurich. And the dialog box says Europe/Zurich (CET)
You type :
-ft set Europe/Zurich

**Comment by mahoromax** [comment]
Oh damn. XD
It did work with EST though
thx for the answer !

**Comment by iNgeon** [comment]
The bot is currently offline...
Can\would it be possible to allow users to add their respective timezones in a PM to the bot.
Some people are concerned about sharing their location\privacy!
Please this would be great.

**Comment by jasontjohnson** [comment]
Any movement on this? This is a much needed feature... Thanks!

**Comment by KevinNovak** [comment]
With the recent update, it is now possible to set time zones for other users by using the `-ft set <@user>` command.

See the documentation [here](https://docs.friendtime.ml/commands/user-commands/set#setup-for-another-user) for more information.
