### ISSUE TITLE
user not found

### ISSUE THREAD

**Issue by seventhrunner** [KevinNovak/Friend-Time#71]
a new member of our discord server is attempting to set their time zone, we've checked to make sure they are using the correct format: 

-ft set <zone>

but they are getting an error message that states "user not found"

i'm sorry i dont have any screenshots

**Comment by KevinNovak** [comment]
The new command is just ["-ft set"](https://docs.friendtime.ml/commands/user-commands/set#setup-for-yourself) with nothing after, no timezone after.
