### ISSUE TITLE
Remove unwanted time zones from list mode

### ISSUE THREAD

**Issue by KevinNovak** [KevinNovak/Friend-Time#8]
@weightmanj: "Is there a way to remove a timezone we no longer want. For example if we have called the same timezone under two different locations  Thanks in advance"

**Comment by KevinNovak** [comment]
**Ry** (Discord): "Hey man, can I request you add a limit to amount of stuff to be added to time friend, or make it so only certain people can add a timezone it displays? Also the ability to admin it and remove people adding meme countries would be really nice. When I added it, it was flooded with activity and now I'm not sure if I can actually use it due to spam?"

**Comment by KevinNovak** [comment]
**{DaRk_KinGs} Maverick** (Discord): "Hey dude i really like your time bot, "Friend Time", is there anyway to remove someones timezone on there once they have set it, with me being the owner of the sever of course. if someone sets something incorrect will it stay on the list forever? i have tryed removing the bot and then allowing it back in but it remembers what was set."

**Comment by smagdan** [comment]
Yeah I'm hoping for this functionality too, that would be great.. also the ability to rename timezones?

**Comment by weightmanj** [comment]
Any update on if this is possible or an eta?

**Comment by iNgeon** [comment]
It would be wonderful if it could one day use https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations.

**Comment by jasontjohnson** [comment]
This would be an extremely handy feature. Any updates as to if it can/will be done? Thanks!

**Comment by Cazz0r** [comment]
+1

**Comment by JBlumenberg** [comment]
Id like that as well.

**Comment by KevinNovak** [comment]
With the recent update, "list mode" has been replaced with a **time zone list** (`-ft list`). Servers can add or remove whatever time zones they want to the list using `-ft list <zone>`, up to 10 time zones total. This list will be shown after a time is mentioned in chat (as long as there is at least 1 time zone in the list):

![image](https://user-images.githubusercontent.com/11231402/110254006-36054a80-7f5b-11eb-9e50-c93c9f61f5a1.png)

See the documentation [here](https://docs.friendtime.ml/commands/admin-commands/list) for more information.
